#!/usr/bin/env pwsh
<#
.SYNOPSIS
Install the Cezar factory into a project (.ai/factory), using the project's pinned version.
.EXAMPLE
./scripts/install.ps1 -ProjectPath ../my-project -ProjectType godot
#>
[CmdletBinding()]
param(
    [string]$ProjectPath = (Get-Location).Path,
    [string]$FactoryPath = (Join-Path $PSScriptRoot '..'),
    [string]$ProjectType = 'generic',
    [switch]$DryRun
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'lib.ps1')

$project = Resolve-ProjectPath $ProjectPath
$factory = (Resolve-Path $FactoryPath).Path
$fdir = Get-FactoryDir $project
$configPath = Join-Path $fdir 'factory.config.yaml'

if (-not (Test-Path $configPath)) {
    $tpl = [IO.File]::ReadAllText((Join-Path $factory 'templates/factory.config.yaml')) -replace "`r`n", "`n"
    $tpl = [regex]::Replace($tpl, '\A# GENERATED BY CEZAR-FACTORY\n(#[^\n]*\n)*\n?', "# Project-owned factory configuration. Edit freely; change factory.version to upgrade.`n`n")
    $ver = Get-FactoryVersion $factory
    $tpl = $tpl -replace '(?m)^(\s*version:\s*)"[^"]*"', "`$1`"$ver`""
    $tpl = $tpl -replace '(?m)^(\s*type:\s*).*$', "`${1}$ProjectType"
    if ($DryRun) {
        Write-Host "[DRY-RUN] Would create $configPath"
        $configPath = Join-Path ([IO.Path]::GetTempPath()) "factory-dryrun-$([guid]::NewGuid()).yaml"
        Write-Utf8 $configPath $tpl
    }
    else { Write-Utf8 $configPath $tpl }
}

$r = Invoke-FactorySync -ProjectPath $project -FactoryRoot $factory -ConfigPath $configPath -DryRun:$DryRun
Write-SyncSummary $r -DryRun:$DryRun
if ($r.Blocked) {
    Write-Host 'REFUSED: ambiguous or locally modified managed files; nothing was written.' -ForegroundColor Red
    foreach ($f in @($r.Ambiguous) + @($r.Modified)) { Write-Host "  $f" }
    exit 1
}
Write-Host 'Installation complete.' -ForegroundColor Green
