# Shared helpers for install/update/diff/verify. Dot-source this file.
Set-StrictMode -Version Latest

$script:ManifestName = 'manifest.json'

function Get-DefaultFactoryRoot { (Resolve-Path (Join-Path $PSScriptRoot '..')).Path }

function Get-FactoryDir([string]$ProjectPath) { Join-Path $ProjectPath '.ai/factory' }

function Get-FactoryVersion([string]$FactoryRoot) {
    $v = Join-Path $FactoryRoot 'VERSION'
    if (-not (Test-Path $v)) { throw "VERSION not found in factory source '$FactoryRoot'" }
    (Get-Content -Raw $v).Trim()
}

function Test-SemVer([string]$Value) { $Value -match '^\d+\.\d+\.\d+$' }

# Minimal YAML reader for factory.config.yaml: top-level lists and one nested level of scalars.
function Read-FactoryConfig([string]$Path) {
    if (-not (Test-Path $Path)) { throw "Config not found: $Path" }
    $cfg = [ordered]@{}
    $section = $null
    foreach ($line in (Get-Content $Path)) {
        if ($line -match '^\s*(#.*)?$') { continue }
        if ($line -match '^(\w+):\s*$') { $section = $Matches[1]; $cfg[$section] = $null; continue }
        if ($line -match '^\s+-\s+(.+?)\s*$') {
            if ($null -eq $cfg[$section]) { $cfg[$section] = @() }
            $cfg[$section] = @($cfg[$section]) + ($Matches[1].Trim('"'))
            continue
        }
        if ($line -match '^\s+(\w+):\s*(.*?)\s*$' -and $section) {
            if ($null -eq $cfg[$section]) { $cfg[$section] = [ordered]@{} }
            $cfg[$section][$Matches[1]] = $Matches[2].Trim('"')
        }
    }
    $cfg
}

function Test-FactoryConfig($Config) {
    $errs = @()
    foreach ($k in 'factory', 'workflows', 'skills', 'project', 'validation') {
        if (-not $Config.Contains($k) -or $null -eq $Config[$k]) { $errs += "missing section '$k'" }
    }
    if ($Config.Contains('factory') -and $Config['factory']) {
        $f = $Config['factory']
        if (-not $f.Contains('source')) { $errs += 'factory.source missing' }
        if (-not $f.Contains('version') -or -not (Test-SemVer $f['version'])) { $errs += 'factory.version missing or not x.y.z' }
    }
    $errs
}

function Get-MarkerStyle([string]$RelPath) {
    if ($RelPath -match '\.md$') { return 'html' }
    if ($RelPath -match '\.(ya?ml|ps1)$') { return 'hash' }
    'none'
}

# Remove any existing managed header, return the body (LF endings).
function Remove-Marker([string]$Text, [string]$Style) {
    $t = $Text -replace "`r`n", "`n"
    if ($Style -eq 'html') { $t = [regex]::Replace($t, '\A<!--\s*\nmanaged-by:[\s\S]*?-->\n?', '') }
    elseif ($Style -eq 'hash') { $t = [regex]::Replace($t, '\A# GENERATED BY CEZAR-FACTORY\n(#[^\n]*\n)*', '') }
    $t
}

# Build the installed content (LF line endings) for a source file.
function New-ManagedContent([string]$SourceFile, [string]$RelSource, [string]$Version) {
    $style = Get-MarkerStyle $RelSource
    $raw = [IO.File]::ReadAllText($SourceFile)
    $body = Remove-Marker $raw $style
    switch ($style) {
        'html' { "<!--`nmanaged-by: cezar-factory`nfactory-version: $Version`nsource: $RelSource`n-->`n$body" }
        'hash' { "# GENERATED BY CEZAR-FACTORY`n# factory-version: $Version`n# source: $RelSource`n# DO NOT EDIT DIRECTLY`n$body" }
        default { $raw -replace "`r`n", "`n" }
    }
}

function Get-TextHash([string]$Text) {
    $bytes = [Text.UTF8Encoding]::new($false).GetBytes($Text)
    # Use the provider API so the factory works under both PowerShell 7/.NET
    # and Windows PowerShell 5.1/.NET Framework.
    $sha = [Security.Cryptography.SHA256]::Create()
    try { $digest = $sha.ComputeHash($bytes) }
    finally { $sha.Dispose() }
    ([BitConverter]::ToString($digest) -replace '-', '').ToLower()
}

function Write-Utf8([string]$Path, [string]$Text) {
    $dir = Split-Path $Path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [IO.File]::WriteAllText($Path, $Text, [Text.UTF8Encoding]::new($false))
}

function Get-FeatureOn($Config, [string]$Name) {
    $Config.Contains('features') -and $Config['features'] -and $Config['features'].Contains($Name) -and $Config['features'][$Name] -eq 'true'
}

# Where a factory source file lives inside a project (Cezar's own discovery locations).
#   workflows/X.yaml        -> .ai/cezar/workflows/factory-X.yaml  (workflow name inside is factory-X)
#   skills/S/SKILL.md       -> .ai/skills/S/SKILL.md
#   policies|schemas|scripts-> .ai/factory/<same path>
#   automations/*.json      -> .ai/factory/automations/*.json (applied to Cezar by sync-automations.ps1)
function Get-TargetPath([string]$Rel) {
    if ($Rel -match '^workflows/(.+)$') { return ".ai/cezar/workflows/factory-$($Matches[1])" }
    if ($Rel -match '^skills/(.+)$') { return ".ai/skills/$($Matches[1])" }
    ".ai/factory/$Rel"
}

# Factory scripts that run inside projects (called by workflows/skills).
$script:RuntimeScripts = @('validate-result.ps1', 'route-state.ps1', 'sync-automations.ps1', 'watchdog-automations.ps1', 'create-labels.ps1', 'audit-backlog-labels.ps1', 'validate-automation-catalog.ps1', 'reconcile-backlog.ps1', 'lease.ps1', 'record-local-evaluation.ps1', 'evaluate-local-promotion.ps1', 'local/run-local-job.ps1', 'openhands/validate-job.ps1', 'hindsight/client.py', 'hindsight/recall.ps1', 'hindsight/retain.ps1')

# Desired managed files for a config. Each: Target (project-relative, '/'), Content, Hash.
# A project override at .ai/factory/overrides/<source path> fully replaces the factory file.
function Get-DesiredFiles([string]$FactoryRoot, $Config, [string]$Version, [string]$ProjectPath) {
    $skills = @($Config['skills']); $workflows = @($Config['workflows'])
    $selected = [System.Collections.Generic.List[string]]::new()
    foreach ($s in $skills) {
        $p = "skills/$s/SKILL.md"
        if (-not (Test-Path (Join-Path $FactoryRoot $p))) { throw "Requested skill '$s' not found in factory $Version" }
        $selected.Add($p)
    }
    foreach ($w in $workflows) {
        $p = "workflows/$w.yaml"
        if (-not (Test-Path (Join-Path $FactoryRoot $p))) { throw "Requested workflow '$w' not found in factory $Version" }
        $selected.Add($p)
    }
    foreach ($dir in 'policies', 'schemas', 'routing') {
        foreach ($f in Get-ChildItem (Join-Path $FactoryRoot $dir) -File -Recurse) {
            $selected.Add(($f.FullName.Substring($FactoryRoot.Length).TrimStart([char[]]'\/') -replace '\\', '/'))
        }
    }
    foreach ($sc in $script:RuntimeScripts) { $selected.Add("scripts/$sc") }
    $maint = Get-FeatureOn $Config 'maintenance'
    $labelCleanup = Get-FeatureOn $Config 'backlog_label_cleanup'
    if ($maint -and $workflows -notcontains 'maintenance') { $selected.Add('workflows/maintenance.yaml') }
    if ($labelCleanup -and $workflows -notcontains 'backlog-label-audit') { $selected.Add('workflows/backlog-label-audit.yaml') }
    if ($labelCleanup -and $skills -notcontains 'factory-backlog-label-audit') { $selected.Add('skills/factory-backlog-label-audit/SKILL.md') }
    if ((Get-FeatureOn $Config 'knowledge_extraction') -and $skills -notcontains 'factory-learn') { $selected.Add('skills/factory-learn/SKILL.md') }
    if ((Get-FeatureOn $Config 'backlog_reconciliation') -and $skills -notcontains 'factory-work-backlog') { $selected.Add('skills/factory-work-backlog/SKILL.md') }
    # Automations: only those whose workflow is installed (maintenance only with the feature on).
    $allWorkflows = @($workflows) + $(if ($maint) { 'maintenance' }) + $(if ($labelCleanup) { 'backlog-label-audit' })
    foreach ($f in Get-ChildItem (Join-Path $FactoryRoot 'automations') -File -Filter *.json) {
        $def = Get-Content -Raw $f.FullName | ConvertFrom-Json
        if ($f.BaseName -eq 'maintenance' -and -not $maint) { continue }
        if ($f.BaseName -eq 'backlog-label-audit' -and -not $labelCleanup) { continue }
        $wf = $def.task.workflow -replace '^factory-', ''
        if ($wf -and $allWorkflows -notcontains $wf) { continue }
        $selected.Add("automations/$($f.Name)")
    }
    foreach ($rel in ($selected | Sort-Object -Unique)) {
        $src = Join-Path $FactoryRoot $rel
        $label = $rel
        if ($ProjectPath) {
            $ov = Join-Path (Get-FactoryDir $ProjectPath) "overrides/$rel"
            if (Test-Path $ov) { $src = $ov; $label = "overrides/$rel" }
        }
        $content = New-ManagedContent $src $label $Version
        $target = Get-TargetPath $rel
        [pscustomobject]@{ Target = $target; Content = $content; Hash = (Get-TextHash $content) }
    }
}

function Read-Manifest([string]$FactoryDir) {
    $p = Join-Path $FactoryDir $script:ManifestName
    if (-not (Test-Path $p)) { return $null }
    Get-Content -Raw $p | ConvertFrom-Json
}

function Write-Manifest([string]$FactoryDir, [string]$Version, $Files) {
    $m = [ordered]@{
        factory_version = $Version
        files           = @($Files | ForEach-Object { [ordered]@{ path = $_.Target; sha256 = $_.Hash } })
    }
    Write-Utf8 (Join-Path $FactoryDir $script:ManifestName) (($m | ConvertTo-Json -Depth 5) + "`n")
}

# Hash of a file on disk with LF endings, for drift comparison.
function Get-FileTextHash([string]$Path) {
    Get-TextHash (([IO.File]::ReadAllText($Path)) -replace "`r`n", "`n")
}

function Resolve-ProjectPath([string]$Path) {
    if (-not (Test-Path $Path)) { throw "Project path not found: $Path" }
    (Resolve-Path $Path).Path
}

# Shared sync: reconcile project's .ai/factory against desired files. Returns change summary.
# Ownership rule: only paths listed in the existing manifest may be overwritten/removed. An existing
# file at a desired path that is not in the manifest (and differs) is "ambiguous" and blocks the sync.
function Invoke-FactorySync {
    param([string]$ProjectPath, [string]$FactoryRoot, [string]$ConfigPath, [switch]$DryRun)

    $fdir = Get-FactoryDir $ProjectPath
    $cfg = Read-FactoryConfig $ConfigPath
    $errs = Test-FactoryConfig $cfg
    if ($errs) { throw "Invalid config: $($errs -join '; ')" }
    $pin = $cfg['factory']['version']
    $srcVersion = Get-FactoryVersion $FactoryRoot
    if ($pin -ne $srcVersion) { throw "Config pins factory $pin but factory source is $srcVersion. Update the pin or use a matching factory checkout." }

    $desired = @(Get-DesiredFiles $FactoryRoot $cfg $srcVersion $ProjectPath)
    $manifest = Read-Manifest $fdir
    $owned = @{}
    if ($manifest) { foreach ($f in $manifest.files) { $owned[$f.path] = $f.sha256 } }
    $desiredMap = @{}; foreach ($d in $desired) { $desiredMap[$d.Target] = $d }

    $r = [ordered]@{ Added = @(); Updated = @(); Unchanged = @(); Removed = @(); Ambiguous = @(); Modified = @(); Blocked = $false; FromVersion = $(if ($manifest) { $manifest.factory_version } else { $null }); ToVersion = $srcVersion }
    foreach ($d in $desired) {
        $dest = Join-Path $ProjectPath $d.Target
        if (-not (Test-Path $dest)) { $r.Added += $d.Target; continue }
        $cur = Get-FileTextHash $dest
        if ($cur -eq $d.Hash) { $r.Unchanged += $d.Target; continue }
        if (-not $owned.ContainsKey($d.Target)) { $r.Ambiguous += $d.Target; continue }
        if ($cur -ne $owned[$d.Target]) { $r.Modified += $d.Target; continue }
        $r.Updated += $d.Target
    }
    foreach ($p in $owned.Keys) {
        if ($desiredMap.ContainsKey($p)) { continue }
        $dest = Join-Path $ProjectPath $p
        if (-not (Test-Path $dest)) { continue }
        if ((Get-FileTextHash $dest) -ne $owned[$p]) { $r.Modified += $p } else { $r.Removed += $p }
    }
    $r.Blocked = [bool]($r.Ambiguous.Count -or $r.Modified.Count)
    if ($r.Blocked) { return [pscustomobject]$r }

    if (-not $DryRun) {
        foreach ($d in $desired) { Write-Utf8 (Join-Path $ProjectPath $d.Target) $d.Content }
        foreach ($p in $r.Removed) {
            $dest = Join-Path $ProjectPath $p
            Remove-Item $dest -Force
            $parent = Split-Path $dest -Parent
            while ($parent.Length -gt $ProjectPath.Length + 5 -and (Test-Path $parent) -and -not (Get-ChildItem $parent -Force)) { Remove-Item $parent -Force; $parent = Split-Path $parent -Parent }
        }
        Write-Utf8 (Join-Path $fdir 'VERSION') "$srcVersion`n"
        Write-Manifest $fdir $srcVersion $desired
        # Gitignore fragment (factory-owned, tracked in manifest-free file for projects to append)
        $frag = Join-Path $FactoryRoot 'templates/gitignore.fragment'
        if (Test-Path $frag) { Write-Utf8 (Join-Path $fdir 'gitignore.fragment') ([IO.File]::ReadAllText($frag) -replace "`r`n", "`n") }
    }
    [pscustomobject]$r
}

function Write-SyncSummary($R, [switch]$DryRun) {
    $from = if ($R.FromVersion) { $R.FromVersion } else { '(none)' }
    Write-Host "Factory $from -> $($R.ToVersion)$(if ($DryRun) { ' [DRY-RUN]' })"
    foreach ($k in 'Updated', 'Added', 'Removed', 'Ambiguous', 'Modified') {
        if (@($R.$k).Count) { Write-Host "$k`:"; $R.$k | ForEach-Object { Write-Host "  $_" } }
    }
    Write-Host "Unchanged: $(@($R.Unchanged).Count) files"
    Write-Host 'Project-owned files:'
    Write-Host '  unchanged'
}
